### ISSUE TITLE
Non-explicit recipient matching

### ISSUE THREAD

**Issue by djalliso** [finitepartners/sn-email-filter-subprod#2]
I've identified an issue in the code in which the recipient list can be incorrectly overwritten if the e-mail address of a whitelisted user is a substring of an email address in the original recipient list (e.g. if there is a whitelisted test account bar@web.com and the recipient list contains an address foobar@web.com, it will write bar@web.com to the allowed addresses even though they weren't a recipient).  This can probably be fixed by converting current.recipients to an array before doing indexOf matches.

**Comment by garrett-griffin** [comment]
Fixed in merge on 4/22.
